SET (VERSION_SHORT ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR})
SET (VERSION_FULL ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})

IF (NOT DEFINED PROJECT_TYPES)
	SET (PROJECT_TYPES "Header Library" CACHE STRING "Default artifact build type")
	#SET_PROPERTY (CACHE PROJECT_TYPES PROPERTY STRINGS Header Library Binary)
	MESSAGE (WARN "PROJECT_TYPES not defined, setting default value: '${PROJECT_TYPES}'")
ENDIF ()

MESSAGE (STATUS "Building ${PROJECT_NAME} version ${PROJECT_VERSION} as a ${PROJECT_TYPES} project")
FOREACH (TYPE ${PROJECT_TYPES})
	INCLUDE (${CMAKE_CURRENT_LIST_DIR}/build-type/${TYPE}.cmake)
ENDFOREACH()

OPTION (BUILD_TESTS "Build tests for ${PROJECT_NAME} project" ON)
IF (BUILD_TESTS)
	ENABLE_TESTING ()
	INCLUDE (CTest)
ENDIF ()

INCLUDE (${CMAKE_CURRENT_LIST_DIR}/NSISCPackConfig.cmake) # Para
