SET (PROJECT_CONFIG_FILE "${CMAKE_BINARY_DIR}/${PROJECT_NAME}Config.cmake")
SET (PROJECT_VERSION_FILE "${CMAKE_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake")

IF (NOT EXISTS ${PROJECT_CONFIG_FILE} OR NOT EXISTS ${PROJECT_VERSION_FILE})
	INCLUDE (CMakePackageConfigHelpers)
	CONFIGURE_PACKAGE_CONFIG_FILE (
		"${CMAKE_CURRENT_LIST_DIR}/Config.cmake.in"
		"${PROJECT_CONFIG_FILE}"
		INSTALL_DESTINATION ${LIBRARY_INSTALL_DIR}/${PROJECT_NAME}/cmake
		PATH_VARS
		INCLUDE_INSTALL_DIR
		LIBRARY_INSTALL_DIR
		SYSCONF_INSTALL_DIR
		RUNTIME_INSTALL_DIR)

	WRITE_BASIC_PACKAGE_VERSION_FILE (
		"${PROJECT_VERSION_FILE}"
		COMPATIBILITY SameMajorVersion)

	INSTALL (FILES
		"${PROJECT_CONFIG_FILE}"
		"${PROJECT_VERSION_FILE}"
		DESTINATION ${LIBRARY_INSTALL_DIR}/${PROJECT_NAME}/cmake)

ENDIF ()
