SET (TEST_TARGET ${TARGET_NAME}Test)

ADD_EXECUTABLE (${TEST_TARGET})

AUX_SOURCE_DIRECTORY (${CMAKE_CURRENT_SOURCE_DIR}/test/src _SOURCES)
TARGET_SOURCES (${TEST_TARGET} PRIVATE ${_SOURCES})

FIND_PACKAGE (Catch2 REQUIRED)

TARGET_INCLUDE_DIRECTORIES (${TEST_TARGET}
  PRIVATE
  ${CMAKE_CURRENT_SOURCE_DIR}/include)

TARGET_LINK_LIBRARIES (${TEST_TARGET} ${TARGET_NAME})

ADD_DEPENDENCIES (${TEST_TARGET} ${TARGET_NAME})

IF (EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/test/resources")
  FILE (
    COPY "${CMAKE_CURRENT_SOURCE_DIR}/test/resources"
    DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/test")
ENDIF ()

INCLUDE (CTest)
INCLUDE (Catch)
CATCH_DISCOVER_TESTS (${TEST_TARGET})
