GET_TARGET_PROPERTY (_TYPE ${PROJECT_NAME} TYPE)
IF (NOT "${_TYPE}" STREQUAL "EXECUTABLE")
	MESSAGE (FATAL_ERROR "Test projects MUST be executable")
ENDIF()

AUX_SOURCE_DIRECTORY (${CMAKE_CURRENT_SOURCE_DIR}/src _SOURCES)
TARGET_SOURCES (${PROJECT_NAME} PRIVATE ${_SOURCES})

FIND_PACKAGE (GTest REQUIRED)

GET_PROPERTY (MAIN_TARGET GLOBAL PROPERTY MAIN_TARGET)
TARGET_LINK_LIBRARIES (${PROJECT_NAME} PRIVATE ${GTEST_BOTH_LIBRARIES} ${MAIN_TARGET})
LINK_DIRECTORIES (${PROJECT_NAME} ${CMAKE_BINARY_DIR})

TARGET_INCLUDE_DIRECTORIES (${PROJECT_NAME}
	PRIVATE
		${CMAKE_CURRENT_SOURCE_DIR}/include)

IF (EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/resources")
	FILE (COPY "${CMAKE_CURRENT_SOURCE_DIR}/resources" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")
ENDIF ()

INCLUDE (CTest)
INCLUDE (GoogleTest)
GTEST_ADD_TESTS (TARGET ${PROJECT_NAME} WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
