FIND_PROGRAM (CTEST_COVERAGE_COMMAND NAMES gcov)
FIND_PROGRAM (CTEST_MEMORYCHECK_COMMAND NAMES valgrind)

# CTest dashboard steps
# https://cmake.org/cmake/help/v3.12/manual/ctest.1.html#id19

IF (NOT DEFINED CMAKE_BUILD_TYPE)
	SET (CMAKE_BUILD_TYPE Debug)
ENDIF()
SET (CTEST_CMAKE_COMMAND "cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
	-DCMAKE_MODULE_PATH=${CMAKE_CURRENT_LIST_DIR} \
	--no-warn-unused-cli")

IF (NOT DEFINED CTEST_MODEL)
	SET (CTEST_MODEL Experimental)
ENDIF()
SET (CTEST_COMMAND "ctest -M ${CTEST_MODEL} -T start -T configure -T build -T test")

SET (CTEST_ENVIRONMENT
	"GTEST_COLOR=1"
	"CTEST_OUTPUT_ON_FAILURE=1"
)
