SET (EXTRA_TEST_ARGS ${EXTRA_TEST_ARGS} ${PROJECT_NAME})

# Test framework
FIND_PACKAGE (Catch REQUIRED)
LINK_DIRECTORIES (${Catch_LIBRARY_DIR})
INCLUDE_DIRECTORIES (${Catch_INCLUDE_DIR})
SET (EXTRA_TEST_ARGS ${EXTRA_TEST_ARGS} ${EXTRA_ARGS} Catch)

#Carrega todos os arquivos de código fonte em SOURCE
FILE (GLOB TESTS_SOURCES "${CMAKE_SOURCE_DIR}/test/src/*.cpp")
IF(EXISTS "${CMAKE_SOURCE_DIR}/test/src/main.cpp")
  SET (MAIN_FILE "${CMAKE_SOURCE_DIR}/test/src/main.cpp")
ENDIF()

SET (CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}")
INCLUDE (ParseAndAddCatchTests)

FOREACH(SOURCE_FILE ${TESTS_SOURCES})
  GET_FILENAME_COMPONENT (FILE_NAME ${SOURCE_FILE} NAME_WE)
  IF (NOT FILE_NAME MATCHES "main")
    SET_PROPERTY (DIRECTORY PROPERTY COMPILE_DEFINITIONS __TEST_CLASS__=${FILE_NAME})
    MESSAGE (STATUS "Preparando classe de teste: ${FILE_NAME}")
    ADD_EXECUTABLE (${FILE_NAME} ${SOURCE_FILE} ${MAIN_FILE})
    TARGET_LINK_LIBRARIES (${FILE_NAME} ${EXTRA_TEST_ARGS})
    ParseAndAddCatchTests(${FILE_NAME})
  ENDIF()
ENDFOREACH()

IF (EXISTS "${CMAKE_SOURCE_DIR}/test/resources")
  FILE (COPY "${CMAKE_SOURCE_DIR}/test/resources" DESTINATION "${CMAKE_BINARY_DIR}")
ENDIF ()
