SET (EXTRA_TEST_ARGS ${EXTRA_TEST_ARGS} ${PROJECT_NAME})

FIND_PACKAGE (GTest REQUIRED)
INCLUDE_DIRECTORIES (${GTEST_INCLUDE_DIRS})
SET (EXTRA_TEST_ARGS ${EXTRA_TEST_ARGS} ${GTEST_BOTH_LIBRARIES} ${EXTRA_ARGS})

#Carrega todos os arquivos de código fonte em SOURCE
FILE (GLOB TESTS_SOURCES "test/src/*.cpp")
SET (MAIN_FILE "test/src/main.cpp")

FOREACH(SOURCE_FILE ${TESTS_SOURCES})
  GET_FILENAME_COMPONENT (FILE_NAME ${SOURCE_FILE} NAME_WE)
  IF (NOT FILE_NAME MATCHES "main")
    SET_PROPERTY (DIRECTORY PROPERTY COMPILE_DEFINITIONS __TEST_CLASS__=${FILE_NAME})
    MESSAGE (STATUS "Preparando classe de teste: ${FILE_NAME}")
    ADD_EXECUTABLE (${FILE_NAME} ${SOURCE_FILE} ${MAIN_FILE})
    TARGET_LINK_LIBRARIES (${FILE_NAME} ${EXTRA_TEST_ARGS})
    ADD_TEST (${FILE_NAME} ${FILE_NAME})
  ENDIF()
ENDFOREACH()

IF (EXISTS "test/resources")
  FILE (COPY "test/resources" DESTINATION "${CMAKE_BINARY_DIR}")
ENDIF ()
