SET (PROJECT_TEST_NAME ${PROJECT_NAME}Test CACHE STRING "Default project test name")
#SET_PROPERTY (DIRECTORY PROPERTY COMPILE_DEFINITIONS __TEST_CLASS__=${PROJECT_TEST_NAME})
SET (EXTRA_TEST_ARGS ${EXTRA_TEST_ARGS})

ENABLE_TESTING ()

FIND_PACKAGE (GTest REQUIRED)
INCLUDE_DIRECTORIES (${GTEST_INCLUDE_DIRS})
SET (EXTRA_TEST_ARGS ${EXTRA_TEST_ARGS} ${GTEST_BOTH_LIBRARIES})

INCLUDE_DIRECTORIES (${CMAKE_SOURCE_DIR}/src)
LINK_DIRECTORIES (${CMAKE_BINARY_DIR} ${EXTERNAL_LIBRARY_DIR})

FILE (GLOB TESTS_SOURCES "${CMAKE_SOURCE_DIR}/test/src/*.c*")

IF (EXISTS "${CMAKE_SOURCE_DIR}/test/resources")
	FILE (COPY "${CMAKE_SOURCE_DIR}/test/resources" DESTINATION "${CMAKE_BINARY_DIR}")
ENDIF ()

ADD_EXECUTABLE (${PROJECT_TEST_NAME} ${TESTS_SOURCES})
TARGET_LINK_LIBRARIES (${PROJECT_TEST_NAME} ${EXTRA_TEST_ARGS} ${PROJECT_NAME})

INCLUDE (GoogleTest)
GTEST_ADD_TESTS (TARGET ${PROJECT_NAME}Test)
