FIND_PROGRAM (CTEST_COVERAGE_COMMAND NAMES gcov)
FIND_PROGRAM (CTEST_MEMORYCHECK_COMMAND NAMES valgrind)

SET (CTEST_CMAKE_COMMAND "cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
	-DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH} \
	-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} \
	--no-warn-unused-cli")

SET (CTEST_COMMAND "ctest -M ${MODEL} -T start -T configure -T build -T test")

SET (CTEST_ENVIRONMENT
	"GTEST_COLOR=1"
	"CTEST_OUTPUT_ON_FAILURE=1"
)
