# Configurações de empacotamento do projeto

SET (CPACK_GENERATOR "NSIS")
SET (CPACK_NSIS_MODIFY_PATH OFF)
SET (CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
SET (CPACK_NSIS_DISPLAY_NAME "${PROJECT_NAME}-${VERSION_MAJOR}.${VERSION_MINOR}")
SET (CPACK_NSIS_PACKAGE_NAME "${PROJECT_NAME}-${VERSION_MAJOR}.${VERSION_MINOR}")

SET (CPACK_PACKAGE_VERSION "${VERSION_MAJOR}.${VERSION_MINOR}")
SET (CPACK_PACKAGE_VERSION_MAJOR "${VERSION_MAJOR}")
SET (CPACK_PACKAGE_VERSION_MINOR "${VERSION_MINOR}")
SET (CPACK_PACKAGE_VERSION_PATCH "${VERSION_PATCH}")
SET (CPACK_PACKAGE_NAME "${PROJECT_NAME}" CACHE STRING "Default package name")
SET (CPACK_PACKAGE_VENDOR "BioLogica Sistemas S.A" CACHE STRING "Default package vendor name")
SET (CPACK_PACKAGE_DESCRIPTION_SUMMARY "" CACHE STRING "Short description summary")
SET (CPACK_PACKAGE_INSTALL_DIRECTORY "BioLogica Sistemas\\\\${PROJECT_NAME}" CACHE STRING "Default installation directory")
SET (CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}-${VERSION_FULL}" CACHE STRING "Package file name without extension")

# Componentes disponíveis definidos no projeto
SET (CPACK_COMPONENTS_ALL
	applications
	libraries
	headers
	documentation)

# CPACK_ALL_INSTALL_TYPES é apenas para NSIS
SET (CPACK_ALL_INSTALL_TYPES
	Full
	Developer)

SET (CPACK_COMPONENT_GROUP_RUNTIME_EXPANDED ON)
SET (CPACK_COMPONENT_GROUP_DEVELOPMENT_EXPANDED ON)

# Application
SET (CPACK_COMPONENT_APPLICATIONS_DISPLAY_NAME	"${PROJECT_NAME} Application")
# applications depends esta dando erro porque não há binários a serem instalados
#SET (CPACK_COMPONENT_APPLICATIONS_DEPENDS		libraries)
SET (CPACK_COMPONENT_APPLICATIONS_GROUP			"Runtime")
SET (CPACK_COMPONENT_APPLICATIONS_INSTALL_TYPES	Full)

# Libraries
SET (CPACK_COMPONENT_LIBRARIES_DISPLAY_NAME		"${PROJECT_NAME} Libraries")
SET (CPACK_COMPONENT_LIBRARIES_DEPENDS			headers)
SET (CPACK_COMPONENT_LIBRARIES_GROUP			"Development")
SET (CPACK_COMPONENT_LIBRARIES_INSTALL_TYPES	Full Developer)

# Headers
SET (CPACK_COMPONENT_HEADERS_DISPLAY_NAME "${PROJECT_NAME} Headers")
SET (CPACK_COMPONENT_HEADERS_GROUP			"Development")
SET (CPACK_COMPONENT_HEADERS_INSTALL_TYPES	Full Developer)

# Docs
SET (CPACK_COMPONENT_DOCUMENTATION_DISPLAY_NAME		"${PROJECT_NAME} Documentation")
SET (CPACK_COMPONENT_DOCUMENTATION_GROUP			"Development")
SET (CPACK_COMPONENT_DOCUMENTATION_INSTALL_TYPES	Full Developer)

INCLUDE (CPack)
