SET (TNAME ${PROJECT_NAME}Header)

ADD_LIBRARY (${TNAME} INTERFACE)

TARGET_INCLUDE_DIRECTORIES (${TNAME}
	INTERFACE
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
		$<INSTALL_INTERFACE:include>)

INCLUDE (${CMAKE_CURRENT_LIST_DIR}/../Configure.cmake)

INSTALL (
	TARGETS ${TNAME}
	EXPORT ${PROJECT_NAME}Config)

INSTALL (
	DIRECTORY include/
	COMPONENT headers
	DESTINATION include)

UNSET (TNAME)
