SET (TNAME ${PROJECT_NAME}Library)

# Carrega todos os arquivos do diretório src em SOURCE
FILE (GLOB SOURCES "${CMAKE_SOURCE_DIR}/src/*.c*")

ADD_LIBRARY (${TNAME} "${SOURCES}")

SET_TARGET_PROPERTIES (${TNAME} PROPERTIES
	OUTPUT_NAME ${PROJECT_NAME}
	VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}
	SOVERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR})

TARGET_INCLUDE_DIRECTORIES (${TNAME}
	PUBLIC
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
		$<INSTALL_INTERFACE:include>
	PRIVATE
		src)

TARGET_LINK_LIBRARIES (${TNAME} ${EXTERNAL_LIBS})

INCLUDE (${CMAKE_CURRENT_LIST_DIR}/../Configure.cmake)

INSTALL (
	TARGETS ${TNAME}
	EXPORT ${PROJECT_NAME}Config
	LIBRARY DESTINATION lib COMPONENT libraries
	ARCHIVE DESTINATION lib COMPONENT libraries)

UNSET (TNAME)
