SET (TNAME ${PROJECT_NAME}Binary)

# Carrega todos os arquivos do diretório src em SOURCE
FILE (GLOB SOURCES "${CMAKE_SOURCE_DIR}/src/*.c*")

ADD_EXECUTABLE (${TNAME} "${SOURCES}")

TARGET_INCLUDE_DIRECTORIES (${TNAME}
	PUBLIC
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
		$<INSTALL_INTERFACE:include>
	PRIVATE
		src)

TARGET_LINK_LIBRARIES (${TNAME} ${EXTERNAL_LIBS})

INSTALL (
	TARGETS ${TNAME}
	RUNTIME DESTINATION bin	COMPONENT applications)

UNSET (TNAME)
