# Carrega todos os arquivos do diretório src em SOURCE
FILE (GLOB SOURCES "${CMAKE_SOURCE_DIR}/src/*.c*")
ADD_EXECUTABLE (${PROJECT_NAME} "${SOURCES}")

TARGET_INCLUDE_DIRECTORIES (${PROJECT_NAME}
	PUBLIC
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
		$<INSTALL_INTERFACE:include>
	PRIVATE
		src)

