SET (TNAME ${PROJECT_NAME}Header)

ADD_LIBRARY (${TNAME} INTERFACE)

TARGET_INCLUDE_DIRECTORIES (${TNAME} INTERFACE $<INSTALL_INTERFACE:include>)

INSTALL (
	TARGETS ${TNAME}
	EXPORT ${PROJECT_NAME}Config)

INSTALL (
	EXPORT ${PROJECT_NAME}Config
	FILE "${PROJECT_NAME}Config.cmake"
	COMPONENT headers
	DESTINATION lib/cmake)

INSTALL (
	DIRECTORY include/
	COMPONENT headers
	DESTINATION include)

UNSET (TNAME)
