SET (TNAME ${PROJECT_NAME}Header)

ADD_LIBRARY (${TNAME} INTERFACE)

INSTALL (
	TARGETS ${TNAME}
	EXPORT ${PROJECT_NAME}Config)

INSTALL (
	EXPORT ${PROJECT_NAME}Config
	FILE "${PROJECT_NAME}Config.cmake"
	COMPONENT headers
	DESTINATION lib/cmake/${PROJECT_NAME}-${VERSION_SHORT})

INSTALL (
	DIRECTORY include/
	COMPONENT headers
	DESTINATION include)

UNSET (TNAME)
