# Carrega todos os arquivos do diretório src em SOURCE
FILE (GLOB SOURCES "${CMAKE_SOURCE_DIR}/src/*.c*")
ADD_LIBRARY(${PROJECT_NAME} "${SOURCES}")
#IF (UNIX)
	SET_TARGET_PROPERTIES (${PROJECT_NAME} PROPERTIES
		OUTPUT_NAME ${PROJECT_NAME}
		VERSION ${GENERIC_LIB_VERSION}
		SOVERSION ${GENERIC_LIB_SOVERSION})
#ENDIF()

TARGET_INCLUDE_DIRECTORIES (${PROJECT_NAME}
	PUBLIC
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
		$<INSTALL_INTERFACE:include>
	PRIVATE
		src)
