FIND_PROGRAM (CTEST_COVERAGE_COMMAND NAMES gcov)
FIND_PROGRAM (CTEST_MEMORYCHECK_COMMAND NAMES valgrind)
FIND_PROGRAM (CTEST_GIT_COMMAND NAMES git)

SET (CTEST_SOURCE_DIRECTORY "/path/to/project")
SET (CTEST_BINARY_DIRECTORY "${CTEST_SOURCE_DIRECTORY}/build")

IF (NOT EXISTS "${CTEST_SOURCE_DIRECTORY}")
	SET (CTEST_CHECKOUT_COMMAND "${CTEST_GIT_COMMAND} clone git://git.server/project.git ${CTEST_SOURCE_DIRECTORY}")
ENDIF ()

SET (CTEST_UPDATE_COMMAND "${CTEST_GIT_COMMAND}")

SET (CMAKE_EXTRA_ARGS "${CMAKE_EXTRA_ARGS} -DCMAKE_BUILD_TYPE=Debug")
SET (CMAKE_EXTRA_ARGS "${CMAKE_EXTRA_ARGS} -DTARGET_TYPE=Library")

SET (CTEST_CMAKE_COMMAND "cmake ${CMAKE_EXTRA_ARGS}")
SET (CTEST_COMMAND "ctest -D Experimental")

SET (CTEST_START_WITH_EMPTY_BINARY_DIRECTORY TRUE)

SET (CTEST_ENVIRONMENT
	"GTEST_COLOR=1"
	"CTEST_OUTPUT_ON_FAILURE=1"
)
